### ISSUE TITLE
Allow Administrators to use the Webhook's default username. 

### ISSUE THREAD

**Issue by LucesEnBabel** [kalynrobinson/discord_integration#2]
The current behavior (New Thread Discord Nickname) if left blank it will use the Original Poster's name.

Since Discord allows us to customize the Webhook default username it would be nice to have that option.

**Comment by kalynrobinson** [comment]
@LucesEnBabel this should be complete, but it will require you to uninstall and reinstall the plugin.

Feel free to open additional issues for other features you would like to see! I'm always looking to improve my plugins.
