### ISSUE TITLE
Thread Prefix Variable

### ISSUE THREAD

**Issue by LucesEnBabel** [kalynrobinson/discord_integration#5]
This is a feature request.

Please add a "Thread Prefix" variable to embed it into the message ($mybb->input["prefix"]).

Thanks in advance.

**Comment by kalynrobinson** [comment]
I'll see what I can do. (: It will likely be accessed via `$prefix`.

**Comment by kalynrobinson** [comment]
`threadprefix` is now accessible through `$prefix`.

**Comment by kalynrobinson** [comment]
@LucesEnBabel closing this issue as the feature has been completed.
