### ISSUE TITLE
$threadlink is invalid

### ISSUE THREAD

**Issue by PassiveModding** [kalynrobinson/discord_integration#9]
$threadlink provides the wrong url http://passivenation.com/showthread.php?tid=0&pid=0#pid=0
so the thread id is always 0
I have only had this issue when posting new threads however, not replies to a thread

![image](https://user-images.githubusercontent.com/20432486/28410479-2e5672d6-6d81-11e7-90b5-cc03f7533a1b.png)

**Comment by gerardsmit** [comment]
Fixed in PR #10, both on new thread and new reply. Tested on MyBB 1.8.12.
